sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kshitijm3/react-test -f ./client/Dockerfile.dev ./client

script:
  -  - docker run -e CI=true kshitijm3/react-test npm test

after_success:
  - docker build -t kshitijm3/multi-client ./client
  - docker build -t kshitijm3/multi-nginx ./nginx
  - docker build -t kshitijm3/multi-server ./server
  - docker build -t kshitijm3/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kshitijm3/multi-client
  - docker push kshitijm3/multi-nginx
  - docker push kshitijm3/multi-server
  - docker push kshitijm3/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: Multi-Docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-511010676387
  bucket_path: docker-multi
  on:
     branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


